return {
    "folke/trouble.nvim",
    dependencies = { "nvim-tree/nvim-web-devicons" },
    opts = {},
    commander = {
        {
            keys = { 'n', '<leader>trt', { desc = '[T]rouble [t]oggle' } },
            cmd = ':Trouble\n',
            desc = 'trouble -> toggle'
        },
        {
            keys = { 'n', '<leader>trd', { desc = '[T]rouble [d]iagnostics' } },
            cmd = ':Trouble diagnostics\n',
            desc = 'trouble -> diagnostics'
        },
        {
            keys = { 'n', '<leader>xd', { desc = '[D]ocument diagnostics' } },
            cmd = ':Trouble document_diagnostics\n',
            desc = 'trouble -> document | show document diagnostics'
        },
        {
            keys = { 'n', '<leader>xq', { desc = '[Q]uickfix' } },
            cmd = ':Trouble quickfix\n',
            desc = 'trouble -> quickfix | show quickfix list'
        },
        {
            keys = { 'n', '<leader>xl', { desc = '[L]ocation list' } },
            cmd = ':Trouble loclist\n',
            desc = 'trouble -> loclist | show location list'
        },
        {
            keys = { 'n', '<leader>xr', { desc = 'LSP [R]eferences' } },
            cmd = ':Trouble lsp_references\n',
            desc = 'trouble -> references | show LSP references'
        },
    },
}

-- TODO: these cammands are badly generated by AI - fix, make sensible and make work
